### ISSUE TITLE
Remove dark theme

### ISSUE THREAD

**Issue by moustafaelsisy** [nmpeckham/tabletopAudio#6]
#5 was not properly triaged, and shouldn't have been approved. GitHub is a prime example of a website that people use every day happily while enjoying its light theme. Adding a dark theme will make the maintenance of this prime software considerably more difficult, for apparently no gain, as can be concluded from the GitHub example

**Comment by moustafaelsisy** [comment]
+1

Any updates on this?

**Comment by moustafaelsisy** [comment]
OP is right, we really need this resolved for our team as well, someone should work on this

**Comment by DanielPower** [comment]
![image](https://user-images.githubusercontent.com/12166320/95665833-8607ee80-0b2e-11eb-91dd-620dbc1469a8.png)

Excuse me?

**Comment by nmpeckham** [comment]
Closed. Won't do. Make a PR.
